name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install pre-built kernel headers for compilation
      run: sudo apt-get update && sudo apt-get install linux-headers-`uname-r`
    - name: make
      run: make
    - name: make check
      run: make check
